wandb_version: 1

JK:
  desc: null
  value: last
K:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.7.10
      5: 0.10.22
      8:
      - 5
activation:
  desc: null
  value: relu
aggregation:
  desc: null
  value: sum
alpha:
  desc: null
  value: 0.1
data_dir:
  desc: null
  value: data
device:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0.0
epochs:
  desc: null
  value: 30
eval_steps:
  desc: null
  value: 1
heads:
  desc: null
  value: 5
hid_dim:
  desc: null
  value: 64
hidden:
  desc: null
  value: 64
layers:
  desc: null
  value: 2
log_batch_size:
  desc: null
  value: 14
lp_layers:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: appnp
num_virtual_nodes:
  desc: null
  value: 1
patience:
  desc: null
  value: 50
seed:
  desc: null
  value: 3736549884
train_idx:
  desc: null
  value: train20
use_gdc:
  desc: null
  value: false
use_node_embedding:
  desc: null
  value: false
use_valedges_as_input:
  desc: null
  value: 0
